<a href="https://colab.research.google.com/github/Praveensharma05/light-house/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import time

In [ ]:
arr = np.array([1,2,4])
print(arr,type(arr))

[1 2 4] <class 'numpy.ndarray'>


In [ ]:
size = 1_000_000
py_list = list(range(size))
np_arr = np.array(py_list)
start = time.time()
np_arr = np_arr ** 2
end = time.time()
print(f"numpy array time is {end - start} seconds")

numpy array time is 0.003442525863647461 seconds


In [ ]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

#int to float

float_arr = arr.astype(np.float64)
print(float_arr)


(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [6. 7. 8.]]


In [ ]:
#reshaping of array
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped, reshaped.shape)
flattened = arr.flatten()
print(flattened, flattened.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [ ]:
#slicing in numpy

arr = np.array([1,2,4,5,6,7])
print(arr)
sub_arr = arr[1:3]
print(sub_arr)

sub_arr[0] = 100
print(sub_arr)
print(arr)

#

[1 2 4 5 6 7]
[2 4]
[100   4]
[  1 100   4   5   6   7]


In [ ]:
#normalisation

arr = np.array([[1,2,3],[4,5,6]])
print(arr)
mean = np.mean(arr)
print(mean)
std = np.std(arr)
print(std)

normalized_arr = (arr - mean) /std
print(normalized_arr)
mean = np.mean(normalized_arr)
print(mean)
std = np.std(normalized_arr)
print(std)





[[1 2 3]
 [4 5 6]]
3.5
1.707825127659933
[[-1.46385011 -0.87831007 -0.29277002]
 [ 0.29277002  0.87831007  1.46385011]]
-3.700743415417188e-17
1.0
